### ISSUE TITLE
Manage display broken on Content types 

### ISSUE THREAD

**Issue by sinyayadynya** [drupal-tome/bookish#12]
On fresh install, can't visit any content type 'Manage display' page.

**To Reproduce**
1. Run "drush si bookish -y" and login
2. Go to  '/admin/structure/types/manage/blog)'
3. Click on 'Manage display' (/admin/structure/types/manage/blog/display)

`Error: Class "Drupal\responsive_image\Plugin\Field\FieldFormatter\ResponsiveImageFormatter" not found in include() (line 32 of /Users/sahaj/Sites/bookish/web/profiles/contrib/bookish/modules/bookish_admin/modules/bookish_image/src/Plugin/Field/FieldFormatter/BookishResponsiveImageFormatter.php)
#0 /Users/sahaj/Sites/bookish/vendor/composer/ClassLoader.php(571): include()
#1 /Users/sahaj/Sites/bookish/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/Users/sahaj/Si...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('Drupal\\bookish_...')
#3 /Users/sahaj/Sites/bookish/web/core/lib/Drupal/Component/Plugin/Factory/DefaultFactory.php(96): class_exists('Drupal\\bookish_...')
#4 /Users/sahaj/Sites/bookish/web/core/modules/field_ui/src/Form/EntityDisplayFormBase.php(758): Drupal\Component\Plugin\Factory\DefaultFactory::getPluginClass('bookish_respons...', Array)
#5 /Users/sahaj/Sites/bookish/web/core/modules/field_ui/src/Form/EntityDisplayFormBase.php(301): Drupal\field_ui\Form\EntityDisplayFormBase->getApplicablePluginOptions(Object(Drupal\field\Entity\FieldConfig))
#6 /Users/sahaj/Sites/bookish/web/core/modules/field_ui/src/Form/EntityViewDisplayEditForm.php(40): Drupal\field_ui\Form\EntityDisplayFormBase->buildFieldRow(Object(Drupal\field\Entity\FieldConfig), Array, Object(Drupal\Core\Form\FormState))
#7 /Users/sahaj/Sites/bookish/web/core/modules/field_ui/src/Form/EntityDisplayFormBase.php(209): Drupal\field_ui\Form\EntityViewDisplayEditForm->buildFieldRow(Object(Drupal\field\Entity\FieldConfig), Array, Object(Drupal\Core\Form\FormState))
#8 /Users/sahaj/Sites/bookish/web/core/lib/Drupal/Core/Entity/EntityForm.php(106): Drupal\field_ui\Form\EntityDisplayFormBase->form(Array, Object(Drupal\Core\Form\FormState))
#9 [internal function]: Drupal\Core\Entity\EntityForm->buildForm(Array, Object(Drupal\Core\Form\FormState))
#10 /Users/sahaj/Sites/bookish/web/core/lib/Drupal/Core/Form/FormBuilder.php(531): call_user_func_array(Array, Array)
#11 /Users/sahaj/Sites/bookish/web/core/lib/Drupal/Core/Form/FormBuilder.php(278): Drupal\Core\Form\FormBuilder->retrieveForm('entity_view_dis...', Object(Drupal\Core\Form\FormState))
#12 /Users/sahaj/Sites/bookish/web/core/lib/Drupal/Core/Controller/FormController.php(73): Drupal\Core\Form\FormBuilder->buildForm(Object(Drupal\field_ui\Form\EntityViewDisplayEditForm), Object(Drupal\Core\Form\FormState))
#13 [internal function]: Drupal\Core\Controller\FormController->getContentResult(Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\RouteMatch))
#14 /Users/sahaj/Sites/bookish/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array)
#15 /Users/sahaj/Sites/bookish/web/core/lib/Drupal/Core/Render/Renderer.php(564): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#16 /Users/sahaj/Sites/bookish/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure))
#17 /Users/sahaj/Sites/bookish/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array)
#18 /Users/sahaj/Sites/bookish/vendor/symfony/http-kernel/HttpKernel.php(159): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#19 /Users/sahaj/Sites/bookish/vendor/symfony/http-kernel/HttpKernel.php(81): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#20 /Users/sahaj/Sites/bookish/web/core/lib/Drupal/Core/StackMiddleware/Session.php(58): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#21 /Users/sahaj/Sites/bookish/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(48): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#22 /Users/sahaj/Sites/bookish/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#23 /Users/sahaj/Sites/bookish/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#24 /Users/sahaj/Sites/bookish/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(48): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#25 /Users/sahaj/Sites/bookish/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(51): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#26 /Users/sahaj/Sites/bookish/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#27 /Users/sahaj/Sites/bookish/web/core/lib/Drupal/Core/DrupalKernel.php(709): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#28 /Users/sahaj/Sites/bookish/web/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#29 /Users/sahaj/Sites/bookish/vendor/drush/drush/misc/d8-rs-router.php(46): require('/Users/sahaj/Si...')
#30 {main}`

**Additional context**
Checked with php 7.4, 8.0 and 8.1

Thanks for help!

**Comment by sinyayadynya** [comment]
Just found out that the 'responsive_image' module wasn't enabled during the site install. 
Enabling it manually fix the issue.

**Comment by mortenson** [comment]
@sinyayadynya Good report - maybe this was enabled by a dependency or I just never visit the manage display page, but I don't see responsive_image listed as a dependency anywhere.

**Comment by mortenson** [comment]
Fixed in 1.0.x! Thanks again
