### ISSUE TITLE
Add Lando support, or include detailed Docker instructions?

### ISSUE THREAD

**Issue by gitressa** [drupal-tome/bookish#4]
This looks great, so thanks for working on it.

I use Lando for Drupal development, since it removes many of the complexities of Docker. With Lando, I got to the `drush runserver` and `drush uli -l 127.0.0.1:8888` bit, but I get a "Unable to connect" at `127.0.0.1:8888` and the Lando address `tome.lndo.site` also hangs ... Would it be possible to add Lando and DDEV support?

Alternatively, perhaps the actual commands to get the Tome Docker image running could be added in [README.md](https://github.com/drupal-tome/bookish#readme), where it now says this?

> Alternatively you can run the commands below using the [mortenson/tome Docker image](https://github.com/drupal-tome/tome-docker). See the [Docker script documentation](https://github.com/drupal-tome/tome-project/#docker) for reference.

**Comment by mrconnerton** [comment]
I've installed it with ddev and works 100% so far.

**Comment by gitressa** [comment]
Thanks for sharing that @mrconnerton, I just assumed wrongly that since it didn't work with Lando, it was the same for DDEV, obviously not ...

Do you mind sharing the commands you use to get an instance up and running in DDEV?

**Comment by mrconnerton** [comment]
I don't quite remember the exact steps but it was something along the lines of

`composer create-project drupal-tome/tome-project bookish --stability dev --no-interaction`
`cd bookish`
`ddev config`
	Select drupal 9, web root, etc like a typical site.
`ddev start`
`ddev composer require drupal-tome/bookish`
`ddev drush tome:init` # Select Bookish in the prompt
`ddev tome:install`

Then https://bookish.ddev.site good to go.

Now I realize now that the install is actually using sqlite instead of the mariadb database with ddev cause I didn't actually check the settings.php that was generated during install, but regardless it still works just fine. I tested exporting the static site. I used https://bookish.ddev.site and the preview worked nice.

**Comment by mrconnerton** [comment]
I prefer more of a whole skeleton project approach so I slapped D9, ddev, bookish and tome together at https://github.com/mrconnerton/bookish

**Comment by gitressa** [comment]
Thanks for sharing your steps, those are also more or less the same ones I tried.

Except I also ran the last `tome:install` command, since I figured that `tome:init` only initiates the project, but don't install. It turns out it does. What threw me off was that the web site was hanging, which made me conclude that `tome:install` was also needed. I updated PHP to 8.1, since I was getting blocked by Composer from using PHP 8.0:

```
Fatal error: Composer detected issues in your platform:
Your Composer dependencies require a PHP version ">= 8.1.0".
You are running 8.0.19. in /app/vendor/composer/platform_check.php on line 24
```

It was hanging because the dblog was getting pummeled with PHP 8.1 warnings (`Deprecated function: Implicit conversion from float 130.73999999999998 to int loses precision in
Drupal\bookish_image\Plugin\ImageEffect\BookishImageEffect->saturation()`) making the file in `web/sites/default/files/.ht.sqlite` balloon. I had to stop Lando to stop it growing any more. It reached 2,6G.

So after running `tome:install`, I got a cryptic error about SQLite missing:

```
Error Output:
  ================
[warning] Program sqlite3 not found. Proceed if you have already created or emptied the Drupal database. [notice] Starting Drupal installation. This takes a while.
In SiteInstallCommands.php line 152:
Drush was unable to drop all tables because `sqlite3` was not found, and therefore Drupal threw an AlreadyInstalled
Exception. Ensure `sqlite3` is available in your PATH.
```

The work-around was disabling the PHP 8.1 constraint by changing `80100` to `80000` in `vendor/composer/platform_check.php`:
```
if (!(PHP_VERSION_ID >= 80000)) {
    $issues[] = 'Your Composer dependencies require a PHP version ">= 8.1.0".
```

Now I can install with this, and it works:
```
composer create-project drupal-tome/tome-project --stability dev --no-interaction
cd tome-project
lando init --recipe drupal9 --name tome-project --source cwd --webroot web
lando start
lando composer require drupal-tome/bookish
lando drush tome:init # Select Bookish in the prompt
```

**Comment by gitressa** [comment]
I have created [Is PHP 8.1 now required for Drupal 9.3?](https://www.drupal.org/project/drupal/issues/3284116) for the PHP 8.1 problem, which is probably not related to Bookish, but still nice to get sorted out.

**Comment by gitressa** [comment]
As I expected, Tome/Bookish was not to blame, but a PHP mismatch: I had 8.1 installed on my machine, while using PHP 8.0 in Lando.
