### ISSUE TITLE
vendor/bin/drush tome:install fails with SQLite error

### ISSUE THREAD

**Issue by gitressa** [drupal-tome/bookish#9]
**Describe the bug**
Running `vendor/bin/drush tome:install` on existing installation fails with an SQLite error.

```
$ vendor/bin/drush tome:install -y

 // You are about to DROP all tables in your local database and re-install Tome. Do you want to continue?: yes. 

In SiteProcess.php line 214:
 
The command "/home/user/my_site/vendor/bin/drush site-install bookish --yes --sites-subdir=default --uri=default --root=/home/user/my_site/web" failed. 
 
Exit Code: 1(General error) 
 
 Working directory: 
 
 Output: 
 ================
 // Do you want to continue?: yes. 
 
 Error Output: 
 ================ 
 [warning] Program sqlite3 not found. Proceed if you have already created or emptied the Drupal database. 
 [notice] Starting Drupal installation. This takes a while. 
 
 In SiteInstallCommands.php line 152: 
 
 Drush was unable to drop all tables because `sqlite3` was not found, and therefore Drupal threw an AlreadyInstalledException. Ensure `sqlite3` is available in your PATH.
```

**To Reproduce**
1. Install with these commands:
```
composer create-project drupal-tome/tome-project my_site --stability dev --no-interaction
cd my_site
composer require drupal-tome/bookish
vendor/bin/drush tome:init # Select Bookish in the prompt
vendor/bin/drush runserver
vendor/bin/drush uli -l 127.0.0.1:8888
```
2. Run `vendor/bin/drush tome:install -y`

**Expected behavior**
Tome and Bookish was re-installed.

**Additional context**
- OS: Ubuntu 20.04.3
- PHP packages:
```
$ dpkg --get-selections | grep -i php # installed php versions
php-cli						install
php-common					install
php-curl					install
php-gd						install
php-mbstring					install
php-sqlite3					install
php-xml						install
php8.1-cli					install
php8.1-common					install
php8.1-curl					install
php8.1-gd					install
php8.1-mbstring					install
php8.1-opcache					install
php8.1-readline					install
php8.1-sqlite3					install
php8.1-xml					install
```

**Comment by mortenson** [comment]
Is sqlite3 available in your Ubuntu installation? It's possible you have the PHP extensions but not the sqlite3 binary.

**Comment by gitressa** [comment]
Thanks @mortenson, nice catch! I didn't realize I had to also install SQLite itself, but running `sudo apt install sqlite3` fixed it, and `drush tome:install -y` now completes successfully.

It's interesting: Tome/Bookish and Drupal Quick-Install have always worked without SQLite itself installed on my machine, just the PHP extension, until now ...

But since I can now re-install successfully with `drush tome:install -y` I can't see that it does anything. For example, newly created content remains, as does the configuration, such as an added field ... Is this the expected behavior? I would expect a reset of content and config, and getting a fresh site with the default content, as after running `drush tome:init`.

Extra question: When building fresh Drupal instances, I like to copy-paste all commands in one go encapsulated between brackets, to ensure processes execute in an orderly fashion, and sit back and see the process complete, without having to copy-paste each line individually. Like this:

```
(
composer create-project drupal-tome/tome-project my_site --stability dev --no-interaction
cd my_site
composer require drupal-tome/bookish
drush tome:init bookish
drush runserver
)
```

This doesn't work currently, since `drush tome:init` requires interaction. Would it be possible to allow a parameter for `tome:init`, for example `drush tome:init bookish`?

**Comment by mortenson** [comment]
> But since I can now re-install successfully with drush tome:install -y I can't see that it does anything. For example, newly created content remains, as does the configuration, such as an added field ... Is this the expected behavior?

This is the "magic" of Tome Sync - every time you edit content or config it automatically exports it to a file, so when you run `drush tome:install` your site is rebuilt in, hopefully, exactly the same way. To see how it works better, you can use Git to track your changes. You should be able to see files added/modified/removed as you click around in Drupal. The point of this feature is to make it so that you don't require a persistent database, and store everything in Git.

> This doesn't work currently, since drush tome:init requires interaction

There's an issue for this here: https://github.com/drupal-tome/tome_drush/issues/1, but I never got around to implementing it. It doesn't have to be implemented the way frob outlined in that issue either, I think `in_array` would be fine to verify that the profile exists. I might work on this next week too but not sure.

**Comment by gitressa** [comment]
> This is the "magic" of Tome Sync - every time you edit content or config it automatically exports it to a file, so when you run drush tome:install your site is rebuilt in, hopefully, exactly the same way.

Thanks for clarifying. That is actually bordering magical, and also explains another thing I was trying to grok -- if the `sqlite` database had to be checked into Git, to ferry content around, which seemed untenable to me. The automatic solution you have created is extremely elegant.

It's super impressive to add a field or some content, and see it reflected instantly in Git:

**Configuration**
```
$ git status
On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
  modified:   config/core.entity_form_display.node.blog.default.yml
  modified:   config/core.entity_view_display.node.blog.default.yml
  modified:   config/core.entity_view_display.node.blog.teaser.yml

Untracked files:
  (use "git add <file>..." to include in what will be committed)
  config/field.field.node.blog.field_magical_link_field.yml
  config/field.storage.node.field_magical_link_field.yml
```

**Content**
```
$ git status
On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
  modified:   content/meta/index.json

Untracked files:
  (use "git add <file>..." to include in what will be committed)
  content/file.7226d27a-1469-4b96-8aa5-5ae5e2a8f316.json
  content/node.c262722f-fc19-4e6a-bce2-8f1e4b5cf1f9.json
  content/path_alias.7fdfb45b-d631-4957-a489-c364580b36a2.json
  content/taxonomy_term.954842f1-cbfe-480f-90d4-d9ef9c8d5de4.json
  content/taxonomy_term.cbe8fefb-7264-47d9-a56e-deefbb374a99.json
  files/public/2022-06/
```

So cool :-)

> There's an issue for this here: drupal-tome/tome_drush#1, but I never got around to implementing it.

Thanks for the link, I am glad to see there is already an issue. I have subscribed to it, and will be ready to try out any updates, whenever you have time to look at it, be it next week or later. Have a great day!
